### ISSUE TITLE
Increase the card drop area on empty lists

### ISSUE THREAD

**Issue by Kaligule** [libreboard/libreboard#83] opened 2015-01-18 11:16 UTC
When I click on "add a card.." in the empty list everxthing works. I assume this creates a card of temporarly existence.

**Comment by mquandalle** [comment] 2015-01-18 12:51
I cannot reproduce this bug. Could you provide more details?

**Comment by Kaligule** [comment] 2015-01-18 14:07
Hmmm, It seems the mistake was on my side. I tried to drag the card on the "add a card" button, not on the list headline. This doesn't work in Libreboard (it does in Trello).
So this is not really a bug. Sorry.

**Comment by mquandalle** [comment] 2015-01-18 14:11
I imagine we can improve the user experience here.

**Comment by mquandalle** [comment] 2015-05-31 23:27
Fixed in 6db01bb3c7bbcf3e5451dd828d3d0932eb5efec3.

**Closed by mquandalle** 2015-05-31 23:27 UTC
Labels: feature, UI/UX
