### ISSUE TITLE
Add members to a board fails

### ISSUE THREAD

**Issue by gierschv** [libreboard/libreboard#148] opened 2015-03-16 10:18 UTC
Can be reproduced for example with the Docker image:

* Add Members...
* Type anything in the search field, including an existing username
* On the client side (the loader keeps spinning):
```
a["{\"msg\":\"nosub\",\"id\":\"rT5vWMAoSeXtX9zxh\",\"error\":{\"error\":400,\"reason\":\"Match failed\",\"message\":\"Match failed [400]\",\"errorType\":\"Meteor.Error\"}}"]
["{\"msg\":\"sub\",\"id\":\"rT5vWMAoSeXtX9zxh\",\"name\":\"users/easySearch\",\"params\":[{\"value\":\"grgr\",\"limit\":10,\"props\":{},\"skip\":0}]}"]
a["{\"msg\":\"ready\",\"subs\":[\"giedX2JGxkNtMQEmg\"]}"]
["{\"msg\":\"sub\",\"id\":\"giedX2JGxkNtMQEmg\",\"name\":\"users/easySearchCount\",\"params\":[]}"]
```
* On the server side:
```
Exception from sub kbcRq92CTp2KLMZNF Error: Match error: Failed Match.OneOf or Match.Optional validation
    at checkSubtree (packages/check/match.js:244:1)
    at check (packages/check/match.js:32:1)
    at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:238:1)
    at [object Object]._.extend.find (packages/mongo/collection.js:274:1)
    at Object.methods.search (packages/matteodem:easy-search/lib/searchers/mongo.js:52:1)
    at [object Object].<anonymous> (packages/matteodem:easy-search/lib/easy-search-common.js:65:1)
    at packages/matb33:collection-hooks/collection-hooks.js:214:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._handler (packages/matb33:collection-hooks/collection-hooks.js:213:1)
    at packages/check/match.js:109:1
Sanitized and reported to the client as: Match failed [400]
```

**Comment by brauliobo** [comment] 2015-06-13 01:00
+1

**Comment by ePirat** [comment] 2015-06-13 12:47
It seems this is fixed in the current development version? At least I am not able to reproduce it anymore with latest master.

**Comment by james-portman** [comment] 2015-06-18 21:55
Works for me now on latest master

**Comment by mko-x** [comment] 2015-07-08 01:15
Cannot reproduce with latest master. 

As there is no official Docker image yet it should work if you build on your own. May cause problems on several machines - see #164

**Closed** 2015-08-28 03:40 UTC
Labels: Bug, Contribute:Reproduction-needed
